"""20250622_143941_core_add_system_prompts

Revision ID: f9ce3b275c4a
Revises: 20250621_115822_core
Create Date: 2025-06-22 14:39:42.731420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9ce3b275c4a'
down_revision: Union[str, None] = '20250621_115822_core'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('user_requirements', sa.Text(), nullable=True),
    sa.Column('generation_context', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('parent_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['parent_version_id'], ['system_prompts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('idx_youtube_chunks_embedding_cosine'), table_name='youtube_chunks', postgresql_using='hnsw')
    op.drop_index(op.f('idx_youtube_chunks_embedding_l2'), table_name='youtube_chunks', postgresql_using='ivfflat')
    op.drop_constraint(op.f('unique_project_video_chunk'), 'youtube_chunks', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('unique_project_video_chunk'), 'youtube_chunks', ['project_slug', 'video_id', 'chunk_index'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_youtube_chunks_embedding_l2'), 'youtube_chunks', ['embedding'], unique=False, postgresql_using='ivfflat')
    op.create_index(op.f('idx_youtube_chunks_embedding_cosine'), 'youtube_chunks', ['embedding'], unique=False, postgresql_using='hnsw')
    op.drop_table('system_prompts')
    # ### end Alembic commands ###